name: separate
description: Separates list elements by conditionally inserting new elements.
version: 1.0.2
repository: https://github.com/mase7569/dart_separate

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  collection: ^1.0.0
